services:
  # cipo_bot:
  #   # NO BUILD CONTAINER - RUN LOCAL
  #   #image: almasnurbayev/go_cipo_bot:latest
  #   image: golang:1.24.3-alpine3.20
  #   working_dir: /app
  #   environment:
  #     - TZ=Asia/Almaty
  #     - ENV=${ENV}
  #     - BOT_TOKEN=${BOT_TOKEN}
  #     - BOT_TIMEOUT=${BOT_TIMEOUT}
  #     - POSTGRES_TIMEOUT=${POSTGRES_TIMEOUT}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #     - POSTGRES_PORT=${POSTGRES_PORT}
  #     - POSTGRES_HOST=${POSTGRES_HOST}
  #     - SECRET_KEY=${SECRET_KEY}
  #   volumes:
  #     - .:/app
  #     - /etc/localtime:/etc/localtime:ro
  #   command: go run cmd/bot/main.go -configEnv ./.env
  #   ports:
  #     - 8443:8443
  #   restart: unless-stopped
  #   depends_on:
  #     - cipo_bot_postgres

  cipo_bot_postgres:
    image: postgres:17.3-alpine3.21
    #container_name: cipo_backend_postgres
    restart: always
    environment:
      - TZ='Asia/Qyzylorda'
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      # - '${HTTP_PORT}:${HTTP_PORT}'
      - '${POSTGRES_PORT}:5432'
    command: ['postgres', '-c', 'config_file=/etc/postgresql/postgresql.conf']
    volumes:
      - ./pg_conf/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./volume_db/:/var/lib/postgresql/data

  kafka:
    image: bitnami/kafka:4.0.0
    container_name: kafka
    hostname: kafka
    ports:
      - '9094:9094' # only for access from outside
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:9094,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LOG_RETENTION_DAYS=100
      - KAFKA_CFG_LOG_RETENTION_BYTES=104857600
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ./volume_kafka:/bitnami/kafka

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    # networks:
    #   - kafka-net
    ports:
      - '8080:8080' # Только Kafka UI доступна снаружи
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: 'true'
    depends_on:
      - kafka
