CREATE TABLE IF NOT EXISTS kassa (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,
  snumber TEXT NOT NULL UNIQUE,
  znumber TEXT NOT NULL UNIQUE,
  knumber TEXT, /* может быть пустым если ОФД не Jusan а другой */
  name_kassa TEXT NOT NULL,
  organization_id BIGINT NOT NULL REFERENCES organizations(id),
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS kassa_idx ON kassa (knumber, snumber);