CREATE TABLE IF NOT EXISTS tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,
  bin TEXT NOT NULL,
  token TEXT NOT NULL,
  exp BIGINT NOT NULL,
  nbf BIGINT NOT NULL,
  working bool ,
  created_at timestamptz DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS tokens_idx ON tokens (bin, exp, created_at);